<?php
/**
 * CardTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reach's Drop-In API
 *
 * API definition for Reach's Drop-In API's. This version of the OpenAPI is intended for use with code generation tools.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.34
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CardTest Class Doc Comment
 *
 * @category    Class
 * @description Payment details for Card type. Must be supplied if Payment.Type is CARD
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Card"
     */
    public function testCard()
    {
    }

    /**
     * Test attribute "stash_id"
     */
    public function testPropertyStashId()
    {
    }

    /**
     * Test attribute "return_url"
     */
    public function testPropertyReturnUrl()
    {
    }

    /**
     * Test attribute "bin"
     */
    public function testPropertyBin()
    {
    }

    /**
     * Test attribute "last_four"
     */
    public function testPropertyLastFour()
    {
    }

    /**
     * Test attribute "expiry"
     */
    public function testPropertyExpiry()
    {
    }
}
