# name: PHP Composer

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * SUN'
  push:
    branches: [ main ]
    paths:
      - ./.github/workflows/assets/swagger.yaml

env:
  SWAGGER_URL: ./.github/workflows/assets/swagger.yaml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v1

    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo Auto generating the client

        echo debug: setup the paths for autogeneration
        output_dir=$(mktemp -d)

        echo debug: download the swagger app
        curl -o openapi-generator-cli.jar https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.0.1/openapi-generator-cli-6.0.1.jar

        echo debug: build the client to ${output_dir}
        java  -jar openapi-generator-cli.jar generate \
              -i ${{ env.SWAGGER_URL }} \
              -g php \
              --git-user-id withreach \
              --git-repo-id reach-client-php \
              -o ${output_dir}

        echo debug: convert the output directory to our github repo
        cp -r ${PWD}/{.git,.github} ${output_dir}
        cd ${output_dir}
        git checkout -b 'github-action'
        git add -A

        echo debug: commit the new client to a branch and create a pr or die
        if ! git commit -m 'autogenerated'; then
          echo info: nothing to commit
          exit 0
        fi
        git push -f origin 'github-action'
        gh pr create --title 'autogenerated code' --body '' --head github-action --base main || echo info: PR likely exists
