name: PHP Composer

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v1

    - run: |
        output_dir=$(mktemp -d)
        gen_dir=${output_dir}/${SwaggerClient-php}
        curl -o swagger-codegen-cli.jar https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.34/swagger-codegen-cli-3.0.34.jar
        java  -jar swagger-codegen-cli.jar generate \
              -i https://petstore.swagger.io/v2/swagger.json \
              -l php \
              -o ${output_dir}
        cp -r ${PWD}/{.git,.github} ${gen_dir}
        cd ${gen_dir}
        git checkout -b 'github-action'
        git add -A 
        git commit -m 'autogenerate'
        git push -f origin 'github-action'