# name: PHP Composer

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * sun'

env:
  SWAGGER_URL: ./.github/workflows/assets/swagger.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: fregante/setup-git-user@v1

    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo Auto generating the client

        echo debug: setup the paths for autogeneration
        output_dir=$(mktemp -d)
        gen_dir=${output_dir}/SwaggerClient-php

        echo debug: download the swagger app
        curl -o swagger-codegen-cli.jar https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.34/swagger-codegen-cli-3.0.34.jar

        echo debug: build the client to ${output_dir}
        java  -jar swagger-codegen-cli.jar generate \
              -i {{ env.SWAGGER_URL }} \
              -l php \
              -o ${output_dir}

        echo dubug: convert the output directory to our github repo
        cp -r ${PWD}/{.git,.github} ${gen_dir}
        cd ${gen_dir}
        git checkout -b 'github-action'
        git add -A 

        echo debug: commit the new client to a branch and create a pr or die
        git commit -m 'autogenerated' 
        if [ $? -eq 0 ]; then 
          echo info: nothing to commit
          exit 0
        fi
        git push -f origin 'github-action'
        gh pr create --title 'autogenerated code' --body '' --head github-action --base main